### ISSUE TITLE
ThrottleBag.h is missing

### ISSUE THREAD

**Issue by StephanHasler** [roboception/rc_bagthrottler#1]
In file included from ./src/rc_bagthrottler/src/test_throttler.cc:2:0:
./src/rc_bagthrottler/include/rc_bagthrottler/BagThrottler.h:12:41: fatal error: rc_bagthrottler/ThrottleBag.h: No such file or directory
 #include <rc_bagthrottler/ThrottleBag.h>
                                         ^
compilation terminated.

**Comment by flixr** [comment]
`rc_bagthrottler/ThrottleBag.h` is the service header that is generated from `ThrottleBag.srv`.

The test_throttler compiles fine here... could you please provide some more details?

**Comment by StephanHasler** [comment]
I build my workspace now several times. The strange thing is sometimes it works sometimes not.

In my workspace are about 20 packages and it is build with broad parallelism (make -j16 -l16).
So either it is a race condition or some file system latency issue.
When I only have the rc_bagthrottler in the workspace it always worked fine.

I will do some more investigations and provide more information and/or close the ticket.
Currently I think problem is not in your source code.

FYI:
-Ubuntu 14
-ROS Indigo
-cmake version 2.8.12.2
-gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by StephanHasler** [comment]
One issue according to the ros docs on building messages: 
(http://docs.ros.org/api/catkin/html/howto/format2/building_msgs.html)
might be that following line is missing in the CMakeLists.txt:
add_dependencies(bagthrottlertest ${${PROJECT_NAME}_EXPORTED_TARGETS})

The docu says:
A good ROS practice is to collect related messages, services and actions into a separate package with no other API. That simplifies the package dependency graph.
However, you can provide scripts and programs with the message package. If you do, message generation targets need to be built before any programs that depend on them. Every target that directly or indirectly uses one of your message headers must declare an explicit dependency:
add_dependencies(your_program ${${PROJECT_NAME}_EXPORTED_TARGETS})


Since adding this line it always (5 times) worked for me, but of course this is no prove.

**Comment by StephanHasler** [comment]
When I removed the line again it broke.
When adding it again it worked.
When I removed the line again it broke.
When adding it again it worked.

So there is at least some correlation ...

**Comment by flixr** [comment]
Thanks! Should be fixed.

**Comment by StephanHasler** [comment]
Thank you!
